#!/bin/bash

Home=`pwd`
libDir=${Home}/lib
CP=${Home}/bin
CYGWIN_SEP=";"
UNIX_SEP=":"

# Choose separator as appropriate for shell system (Cygwin, otherwise UNIX)
SEP=":"
if [[ $OSTYPE == "cygwin" ]] ; then
    SEP=";"
fi

for i in ${libDir}/*.jar ; do
    CP="${CP}${SEP}$i"
    echo @
done

java -Djava.library.path="/opt/local/lib" -Xms100M -Xmx1024M -classpath $CP $1 $2 $3 $4 $5 $6 $7 $8 $9
